### ISSUE TITLE
TypeError: Object #<bound> has no method 'send'

### ISSUE THREAD

**Issue by tskaggs** [mikermcneil/sails-mandrill#4]
I followed the README:
1. Define Connection in connections.js

```
// Mandrill
  'usemandrill': {
    adapter: 'sails-mandrill',
    // apiKey: process.env.MANDRILL_KEY, // the api key for your mandrill account
    apiKey: 'myAPIkey',
    from: {
      name: 'Team Me',
      email: 'me@myurl.me'
    }
  }
```
1. Add Connection to Model (Email.js)
   >   connections:  ['usemandrill'],

```
  module.exports = {
  connections:  ['usemandrill']
};
```
1. Add function to Controller. (UserController.js)

Just to test, I add the function when user updates profile:

```
update: function (req, res, next) {
        User.update(req.param('id'), req.params.all(), function userUpdated (err) {

            if (err) {
                return res.redirect('/user/edit/' + req.param('id'));
            }

            Email.send({
              to: [{
                name: 'My Name',
                email: 'email@email.com'
              }, {
                name: 'Team Me',
                email: 'info@myemail.me'
              }],
              subject: 'omg i love you guys!!1',
              html: 
                'I can\'t wait to see you all in Chicago<br/>' +
                'I loe you so much!!!! ',
              text: 'text fallback goes here-- in case some recipients (let\'s say the Chipettes)  can\'t receive HTML emails'
            }, function optionalCallback (err) {

              console.log('Email Sent!');
              // If you need to wait to find out if the email was sent successfully,
              // or run some code once you know one way or the other, here's where you can do that.
              // If `err` is set, the send failed.  Otherwise, we're good!
            });


            res.redirect('/user/show/' + req.param('id'));
        });
```

I get the error:

```
/Projects/build/node_modules/sails-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:245
        throw message;      
              ^
TypeError: Object #<bound> has no method 'send'
    at userUpdated (/Projects/build/api/controllers/UserController.js:29:11)
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/dql/update.js:216:9
    at done (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:128:19)
    at /usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:25:16
    at /usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:150:25
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/schema.js:151:44
    at fn (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/callbacksRunner.js:98:5)
    at iterate (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:142:13)
    at Object.async.eachSeries (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:158:9)
    at Object.runner.afterUpdate (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/callbacksRunner.js:101:9)
```

**Comment by rkyleg** [comment]
Hey, I solved this issue by changing this (using sailjs version 0.10.5:

    module.exports = {
        connections:  ['usemandrill']
    }; 

to this:

    module.exports = {
        connection:  ['usemandrill']
    };

**Comment by stenio123** [comment]
Thank you @rkyleg !
